name: shikhor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  font_awesome_flutter: ^10.1.0
  flutter_barcode_scanner: ^2.0.0
  get: 4.6.1
  flutter: 
    sdk: flutter
  webview_flutter: ^3.0.4
  image_picker: ^0.8.5+3
  shared_preferences: ^2.0.15
  geolocator: ^8.2.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

